apiVersion: v1
kind: Service
metadata:
  name: devops-app
  namespace: default
spec:
  selector:
    app: devops-app
  # NodePort 30090 mapeado para a porta 9090 do host via Kind extraPortMappings
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30090
